- blueprint: Package
  identifier: toyota-challenger
  title: null
  properties:
    docsUrl: http://exercitationem.org
    packageManager: Maven
  relations: {}
  team: []
- blueprint: Package
  identifier: toyota-volt
  title: null
  properties:
    docsUrl: https://qui.io
    packageManager: Maven
  relations: {}
  team: []
- blueprint: Package
  identifier: smart-focus
  title: null
  properties:
    docsUrl: https://deserunt.name
    packageManager: PIP
  relations: {}
  team: []
- blueprint: Package
  identifier: bugatti-corvette
  title: null
  properties:
    docsUrl: http://sit.biz
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: bugatti-1
  title: null
  properties:
    docsUrl: https://necessitatibus.info
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: mercedes-benz-a-4
  title: null
  properties:
    docsUrl: https://repellat.name
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: ford-camry
  title: null
  properties:
    docsUrl: http://deserunt.io
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: lamborghini-f-150
  title: null
  properties:
    docsUrl: http://aliquid.net
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: mini-explorer
  title: null
  properties:
    docsUrl: http://error.biz
    packageManager: Maven
  relations: {}
  team: []
- blueprint: Package
  identifier: chevrolet-malibu
  title: null
  properties:
    docsUrl: https://ducimus.io
    packageManager: NPM
  relations: {}
  team: []
- blueprint: Package
  identifier: lamborghini-prius
  title: null
  properties:
    docsUrl: https://deserunt.com
    packageManager: Nuget
  relations: {}
  team: []
- blueprint: Package
  identifier: rolls-royce-xc-90
  title: null
  properties:
    docsUrl: http://repellat.info
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: mazda-challenger
  title: null
  properties:
    docsUrl: https://doloribus.biz
    packageManager: Nuget
  relations: {}
  team: []
- blueprint: Package
  identifier: hyundai-roadster
  title: null
  properties:
    docsUrl: https://at.io
    packageManager: Yarn
  relations: {}
  team: []
- blueprint: Package
  identifier: kia-spyder
  title: null
  properties:
    docsUrl: https://labore.org
    packageManager: NPM
  relations: {}
  team: []
